services:
  app:
    container_name: civix_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=civix_db
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_TOKEN_EXPIRATION=900
      - JWT_REFRESH_EXPIRATION=604800
      - GIN_MODE=release
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
    networks:
      - civix-network

  db:
    container_name: civix_postgres_db
    build:
      context: .
      dockerfile: Dockerfile_postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: civix_db
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - civix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: civix_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - civix-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  civix-network:
    driver: bridge
